name: Unity Build
on:
  push:
    tags:
    - '*'
jobs:
  windows:
    name: Windows Build and Post
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ETdoFresh/Actions/UnityBuild@2019.4.19f1
      with:
        UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        BUILD_NAME: Escapism
        BUILD_TARGET: Windows
    - name: Easy Zip Files
      uses: papeloto/action-zip@v1
      with:
        files: ./Build
        dest: ./Escapism.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Get Filename
      id: get_filename
      run: |
        echo ::set-output name=FILENAME::Escapism${GITHUB_REF#refs/tags/}.zip
        echo ::set-output name=FILEPATH::./Escapism${GITHUB_REF#refs/tags/}.zip
    - name: Echo the version
      run: |
        echo $FILENAME
        echo $FILEPATH
      env:
        FILENAME: ${{ steps.get_filename.outputs.FILENAME }}
        FILEPATH: ${{ steps.get_filename.outputs.FILEPATH }}
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILENAME: ${{ steps.get_filename.outputs.FILENAME }}
        FILEPATH: ${{ steps.get_filename.outputs.FILEPATH }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: $FILEPATH
        asset_name: $FILENAME
        asset_content_type: application/zip
    - name: Upload to Google Drive
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        upload-from: $FILEPATH
        upload-to: /Shared/EscapismBuilds
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }} # For those who set up Google Drive API client ID and secret themselves
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      env:
        FILEPATH: ${{ steps.get_filename.outputs.FILEPATH }}
  webgl:
    name: WebGL Build and Post
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ETdoFresh/Actions/UnityBuild@2019.4.19f1-webgl
      with:
        UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        BUILD_NAME: Escapism
        BUILD_TARGET: WebGL
    - uses: ETdoFresh/Actions/TagDirectory@2019.4.19f1-webgl
    - uses: ETdoFresh/Actions/UploadToGithubPages@2019.4.19f1-webgl
      with:
        WIPEOUT_PREVIOUS_CONTENT: 0
        GITHUB_REPOSITORY: F-in-Chat/EscapismWebGL
        GITHUB_USERNAME: ${{ secrets.UNITY_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.UNITY_TOKEN }}
